pipeline{
    agent any 
        stages {
            stage('hi'){
                steps{
                    echo 'hgwdfljhc'
                }
            }
            stage('fdcja'){
                steps{
                    echo 'lsgdc'
                }
            }
        }
}